DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MPHOTO VARCHAR2(30) DEFAULT 'none.PNG' NOT NULL,
    MBIRTH DATE DEFAULT SYSDATE,
    MGENDER VARCHAR2(30),
    MEMAIL VARCHAR2(30),
    MTEL VARCHAR2(100),
    MADDRESS VARCHAR2(255)
);
SELECT * FROM MEMBER;
--회원가입
--ID중복체크
--로그인전 ID체크
--로그인
--ID로 DTO가져오기
--회원정보수정

